-- DDL generado para el diagrama ER del proyecto impuestoscal
-- Tablas: roles, usuarios, usuario_roles, operaciones_igv, recibos_honorarios, registros_tributarios, trabajadores

-- IMPORTANTE: Ejecutar estos comandos en pgAdmin4 de forma separada:
-- 1. Primero crear la base de datos (ejecutar solo si no existe):
--    CREATE DATABASE xddd;
-- 2. Luego conectarse a la BD "xddd" desde pgAdmin4
-- 3. Ejecutar el resto del script desde aquí:

-- Crear schema
CREATE SCHEMA IF NOT EXISTS bdxd;
SET search_path TO bdxd;

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rut10 VARCHAR(10) NOT NULL,
  tipo_persona VARCHAR(10) NOT NULL,
  clave_sol_hash VARCHAR(255) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  CONSTRAINT uk_usuario_rut10 UNIQUE (rut10)
);

CREATE TABLE usuario_roles (
  rol_id BIGINT NOT NULL,
  usuario_id BIGINT NOT NULL,
  PRIMARY KEY (rol_id, usuario_id)
);

CREATE TABLE operaciones_igv (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo BOOLEAN NOT NULL,
  base_imponible NUMERIC(15,2) NOT NULL,
  fecha_operacion DATE NOT NULL,
  igv NUMERIC(15,2) NOT NULL,
  monto_total NUMERIC(15,2) NOT NULL,
  fecha_actualizacion TIMESTAMP NOT NULL,
  fecha_creacion TIMESTAMP NOT NULL,
  usuario_id BIGINT NOT NULL,
  ruc_tercero VARCHAR(11),
  numero_documento VARCHAR(20) NOT NULL,
  razon_social_tercero VARCHAR(200) NOT NULL,
  descripcion VARCHAR(500),
  tipo VARCHAR(20) NOT NULL
);

CREATE TABLE recibos_honorarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo BOOLEAN NOT NULL,
  fecha_emision DATE NOT NULL,
  monto_neto NUMERIC(15,2) NOT NULL,
  monto_total NUMERIC(15,2) NOT NULL,
  retencion NUMERIC(15,2) NOT NULL,
  fecha_actualizacion TIMESTAMP NOT NULL,
  fecha_creacion TIMESTAMP NOT NULL,
  usuario_id BIGINT NOT NULL,
  cliente_ruc VARCHAR(11),
  numero_recibo VARCHAR(20) NOT NULL,
  cliente_razon_social VARCHAR(200),
  descripcion_servicio VARCHAR(500)
);

CREATE TABLE registros_tributarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo BOOLEAN NOT NULL,
  fecha_vencimiento DATE NOT NULL,
  monto NUMERIC(15,2) NOT NULL,
  fecha_actualizacion TIMESTAMP NOT NULL,
  fecha_creacion TIMESTAMP NOT NULL,
  usuario_id BIGINT NOT NULL,
  tipo_impuesto VARCHAR(80) NOT NULL,
  observaciones VARCHAR(500),
  estado VARCHAR(20) NOT NULL
);

CREATE TABLE trabajadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  activo BOOLEAN NOT NULL,
  aporte_pensionario NUMERIC(15,2),
  fecha_cese DATE,
  fecha_ingreso DATE NOT NULL,
  retencion_quinta_categoria NUMERIC(15,2),
  sueldo_bruto NUMERIC(15,2) NOT NULL,
  sueldo_neto NUMERIC(15,2),
  dni VARCHAR(8) NOT NULL,
  empresa_id BIGINT NOT NULL,
  fecha_actualizacion TIMESTAMP NOT NULL,
  fecha_creacion TIMESTAMP NOT NULL,
  telefono VARCHAR(20),
  afp_nombre VARCHAR(50),
  apellido_materno VARCHAR(100) NOT NULL,
  apellido_paterno VARCHAR(100) NOT NULL,
  email VARCHAR(100),
  nombres VARCHAR(100) NOT NULL,
  direccion VARCHAR(200),
  regimen_pensionario VARCHAR(10) NOT NULL
);

-- Foreign keys
ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_rol FOREIGN KEY (rol_id) REFERENCES roles(id);
ALTER TABLE usuario_roles ADD CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id);
ALTER TABLE operaciones_igv ADD CONSTRAINT fk_op_igv_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id);
ALTER TABLE recibos_honorarios ADD CONSTRAINT fk_rec_hon_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id);
ALTER TABLE registros_tributarios ADD CONSTRAINT fk_reg_trib_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id);
ALTER TABLE trabajadores ADD CONSTRAINT fk_trab_empresa FOREIGN KEY (empresa_id) REFERENCES usuarios(id);

-- Indexes
CREATE INDEX idx_operaciones_usuario ON operaciones_igv(usuario_id);
CREATE INDEX idx_recibos_usuario ON recibos_honorarios(usuario_id);
CREATE INDEX idx_registros_usuario ON registros_tributarios(usuario_id);
CREATE INDEX idx_trabajadores_empresa ON trabajadores(empresa_id);
